repos:

  - repo: https://github.com/psf/black
    rev: v21.9b0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    - hooks:
      - id: flake8
        additional_dependencies: [radon]

  - repo: local
    hooks:
    - id: pytest
      entry: pytest src/tests
